- name: Install Java
  hosts: java
  tasks:
    - name: Apt update
      become: True
      apt:
        update_cache: yes

    - name: Install JRE
      become: True
      apt:
        name: openjdk-17-jre

- name: Run Java petclinic
  hosts: java
  tasks:
      - name: Copy .jar
        copy:
          src: ./spring-petclinic.jar
          dest: ./spring-petclinic.jar

      - name: Run .jar
        command: java -jar ./spring-petclinic.jar
        poll: 0
        async: 3600

  

- name: Install Docker
  hosts: docker
  tasks:
    - name: Pull Docker install script
      become: True
      shell: curl -fsSL https://get.docker.com -o get-docker.sh && chmod +x get-docker.sh

    - name: Install Docker
      shell: ./get-docker.sh

- name: Run Docker petclinic
  hosts: docker
  become: True
  tasks:
    - name: Pull the image
      docker_image: 
        name: bole1709/main:actions
        source: pull
    
    - name: Run the image
      docker_container:
        name: petclinic
        image: bole1709/main:actions
        published_ports: 8080:8080
        privileged: yes
      